---
name: Codecov coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Unit test environment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run coverage
        env:
          TEST_SERVER: ${{ secrets.TEST_SERVER }}
          TEST_ACCOUNT_PHONE: ${{ secrets.TEST_ACCOUNT_PHONE }}
          TEST_ACCOUNT_CODE: ${{ secrets.TEST_ACCOUNT_CODE }}
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
